// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gid.proto

package com.guochenxu.gid.protobuf.java.com.guochenxu.gid.protobuf;

public interface CreateTagReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.guochenxu.gid.protobuf.CreateTagReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  String getTag();
  /**
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>int64 startId = 2;</code>
   * @return The startId.
   */
  long getStartId();

  /**
   * <code>int64 step = 3;</code>
   * @return The step.
   */
  long getStep();

  /**
   * <code>string comment = 4;</code>
   * @return The comment.
   */
  String getComment();
  /**
   * <code>string comment = 4;</code>
   * @return The bytes for comment.
   */
  com.google.protobuf.ByteString
      getCommentBytes();
}
