// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gid.proto

package com.guochenxu.gid.protobuf.java.com.guochenxu.gid.protobuf;

public interface CreateTagRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.guochenxu.gid.protobuf.CreateTagResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
