// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gid.proto

package com.guochenxu.gid.protobuf.java.com.guochenxu.gid.protobuf;

public interface GetSnowIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.guochenxu.gid.protobuf.GetSnowId)
    com.google.protobuf.MessageOrBuilder {
}
