// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gid.proto

package com.guochenxu.gid.protobuf.java.com.guochenxu.gid.protobuf;

public interface PingRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.guochenxu.gid.protobuf.PingResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
